template_type: "housing_strategy"
version: "1.0.0"
metadata:
  name: "UAE Local Home Purchase Strategy"
  description: "Rent initially, purchase UAE property in specified year"
  suitable_for: ["uae"]
  author: "Financial Planning System"

strategy: "buy"

# Rental costs for pre-purchase years
rental:
  monthly_cost: 2000

# Purchase configuration  
purchase:
  target_year: 3
  property_price: 520000
  deposit_percentage: 0.20
  mortgage_rate: 0.045
  mortgage_term_years: 25
  purchase_fees_pct: 0.03 