template_type: "housing_strategy"
version: "1.0.0"
metadata:
  name: "UK Home Purchase Strategy"
  description: "Rent initially, purchase UK property in specified year"
  suitable_for: ["uk"]
  author: "Financial Planning System"

strategy: "buy"

# Rental costs for pre-purchase years
rental:
  monthly_cost: 2100

# Purchase configuration  
purchase:
  target_year: 5
  property_price: 600000
  deposit_percentage: 0.20
  mortgage_rate: 0.0525
  mortgage_term_years: 25
  purchase_fees_pct: 0.03 