# Dubai Local Home - Complete Financial Plan
# Dubai tech graduate buying local home

scenario:
  id: "dubai_local_home"
  name: "Dubai Local Home"
  description: "Dubai tech graduate buying local home"
  version: "2.0.0"
  created: "2025-01-29"

location:
  name: "Dubai, UAE"
  currency: "USD"
  exchange_rate: 1.26
  tax_system: "tax_free"

income:
  base_salary: 90000
  progression:
    type: "yearly_overrides"
    rates:
      1: { salary: 90000, bonus: 0.10, rsu: 0.10 }
      2: { salary: 100000, bonus: 0.10, rsu: 0.10 }
      3: { salary: 110000, bonus: 0.10, rsu: 0.10 }
      4: { salary: 120000, bonus: 0.10, rsu: 0.10 }
      5: { salary: 150000, bonus: 0.10, rsu: 0.10 }
      6: { salary: 169000, bonus: 0.10, rsu: 0.10 }
      7: { salary: 183000, bonus: 0.10, rsu: 0.10 }
      8: { salary: 197000, bonus: 0.10, rsu: 0.10 }
      9: { salary: 213000, bonus: 0.10, rsu: 0.10 }
      10: { salary: 230000, bonus: 0.10, rsu: 0.10 }
  
  rsu_config:
    vesting_schedule: "4_year_cliff"
    ipo_multiplier: 2.0

expenses:
  # Location-specific expenses
  location_expenses:
    rent:
      monthly: 2000
      currency: "USD"
    healthcare:
      monthly: 200
      currency: "USD"
    general_expenses:
      monthly: 2000
      currency: "USD"
    retirement_contribution:
      percentage: 0.0  # No 401k equivalent

  # Universal goal-based expenses
  goals:
    university_fees:
      year: 1
      amount: 16800
      payment_schedule: [5600, 5600, 5600]
      currency: "GBP"
    
    marriage:
      total_cost: 70000
      start_year: 3
      end_year: 4
      currency: "GBP"
    
    child_costs:
      start_year: 7
      one_off_cost: 8500
      ongoing_annual_cost: 10000
      currency: "GBP"
    
    personal_expenses:
      year_1: 6000
      year_2: 9000
      default: 12000
      currency: "GBP"
    
    parental_support:
      before_house: 12000
      after_house: 12000
      house_purchase_year: 5
      currency: "GBP"
    
    travel:
      annual: 3000
      currency: "GBP"
    
    housing:
      strategy: "local_home"
      purchase_year: 3
      base_price: 520000
      price_growth: [0.02, 0.03, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
      deposit_pct: 0.20
      mortgage_rate: 0.045
      mortgage_term_years: 25
      currency: "USD"

assumptions:
  start_year: 2025
  plan_duration_years: 10
  inflation_rate: 0.025
  investment_return_rate: 0.065
  start_age: 24
  student_loan_debt: 57000
  relocation_cost: 11800 