# Dubai Local Home - Version 3.0
# Dubai tech graduate buying local home using composition-based architecture

scenario:
  id: "dubai_local_home"
  name: "Dubai Tech Graduate - Local Home Purchase"
  description: "Work in Dubai while buying local Dubai home"
  version: "3.0.0"
  tags: ["international", "dubai", "tech", "local_home"]
  phase: "international_only"
  jurisdiction: "UAE"

composition:
  # Location Market
  location_market: "uae_dubai"       # References config/markets/locations/uae_dubai.yaml
  
  # Tax System
  tax_system: "tax_free"             # References config/tax_systems/tax_free.yaml
  
  # Salary Progression - Override with exact values from config.py international_scenarios.dubai
  salary_progression:
    template: "tech_worker"          # Use tech worker template as base
    override_type: "complete_array"  # Override entire progression with exact values
    base_salary: 90000
    
    # Exact salary progression from config.py international_scenarios.dubai.salary_progression
    salary_array: [90000, 100000, 110000, 120000, 150000, 169000, 183000, 197000, 213000, 230000]
    
    # Exact bonus progression from config.py international_scenarios.dubai.bonus_rate
    bonus_array: [0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10]
    
    # Exact RSU progression from config.py international_scenarios.dubai.rsu_rate
    rsu_array: [0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10]
  
  # Expense Profile
  expense_profile: "graduate"        # References config/templates/expense_profiles/graduate.yaml
  
  # Housing Strategy
  housing_strategy: "uae_local_home_purchase"  # References config/templates/housing_strategies/uae_local_home_purchase.yaml
  
  # Investment Strategy
  investment_strategy: "balanced"    # References config/templates/investment_strategies/balanced.yaml

# Planning Parameters - From config.py
planning:
  start_year: 2025                  # From config.py start_year
  duration_years: 10                # From config.py plan_duration_years  
  start_age: 24                     # From config.py start_age
  currency: "USD"
  inflation_rate: 0.025             # From config.py inflation_rate
  investment_return_rate: 0.065     # From config.py investment_return_rate
  
  # Initial state
  initial_state:
    student_loan_balance: 57000     # From config.py student_loan_debt
    initial_investments: 0
    initial_property_value: 0
    initial_mortgage: 0 