# New York UK Home - Version 3.0
# New York tech graduate buying UK home using composition-based architecture

scenario:
  id: "new_york_uk_home"
  name: "New York Tech Graduate - UK Home Purchase"
  description: "Work in New York while purchasing and renting out UK home"
  version: "3.0.0"
  tags: ["international", "new_york", "tech", "uk_home"]
  phase: "international_only"
  jurisdiction: "US"

composition:
  # Location Market
  location_market: "us_new_york"     # References config/markets/locations/us_new_york.yaml
  
  # Tax System
  tax_system: "us_federal"           # References config/tax_systems/us_federal.yaml
  
  # Salary Progression - Override with exact values from config.py international_scenarios.new_york
  salary_progression:
    template: "tech_worker"          # Use tech worker template as base
    override_type: "complete_array"  # Override entire progression with exact values
    base_salary: 100000
    
    # Exact salary progression from config.py international_scenarios.new_york.salary_progression
    salary_array: [100000, 120000, 130000, 150000, 180000, 200000, 200000, 200000, 230000, 250000]
    
    # Exact bonus progression from config.py international_scenarios.new_york.bonus_rate
    bonus_array: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
    
    # Exact RSU progression from config.py international_scenarios.new_york.rsu_rate
    rsu_array: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
  
  # Expense Profile
  expense_profile: "graduate"        # References config/templates/expense_profiles/graduate.yaml
  
  # Housing Strategy
  housing_strategy: "uk_home_purchase"  # References config/templates/housing_strategies/uk_home_purchase.yaml
  
  # Investment Strategy
  investment_strategy: "balanced"    # References config/templates/investment_strategies/balanced.yaml

# Planning Parameters - From config.py
planning:
  start_year: 2025                  # From config.py start_year
  duration_years: 10                # From config.py plan_duration_years  
  start_age: 24                     # From config.py start_age
  currency: "USD"
  inflation_rate: 0.025             # From config.py inflation_rate
  investment_return_rate: 0.065     # From config.py investment_return_rate
  
  # Initial state
  initial_state:
    student_loan_balance: 57000     # From config.py student_loan_debt
    initial_investments: 0
    initial_property_value: 0
    initial_mortgage: 0 