# Seattle Year 4 Local Home - Version 3.0
# Multi-phase scenario: UK for 3 years, then Seattle with local home purchase

scenario:
  id: "seattle_year4_local_home"
  name: "Delayed Relocation: Seattle Year 4 - Local Home"
  description: "Work in UK for 3 years, relocate to Seattle in year 4, buy local Seattle home"
  version: "3.0.0"
  tags: ["multi_phase", "delayed_relocation", "seattle", "local_home"]

composition:
  # Multi-phase career progression
  phases:
    # Phase 1: UK Years (Years 1-3)
    uk_phase:
      duration: 3
      location:
        market: "uk"                 # References config/markets/locations/uk.yaml
      
      salary_progression:
        template: "conservative"     # Use conservative UK progression
        override_type: "complete_array"
        base_salary: 45000
        
        # UK phase salary progression (Years 1-3)
        salary_array: [45000, 52000, 60000]
        bonus_array: [0.05, 0.08, 0.10]
        rsu_array: [0.15, 0.18, 0.20]
      
      expense_profile:
        template: "graduate"
        location_overrides:
          rent: { monthly: 2100 }
          healthcare: { monthly: 0 }
          general_expenses: { monthly: 1500 }
          retirement_contribution: { percentage: 0.05 }
      
      life_events:
        - template: "education"
          year: 1
          amount: 16800
          payment_schedule: [5600, 5600, 5600]
        
        - template: "marriage"
          start_year: 3
          end_year: 4
          total_cost: 70000
    
    # Phase 2: Seattle Years (Years 4-10)
    seattle_phase:
      duration: 7
      location:
        market: "us_washington"      # References config/markets/locations/us_washington.yaml
      
      salary_progression:
        template: "tech_worker"      # US tech progression
        override_type: "complete_array"
        base_salary: 110000          # 10% premium for UK experience (salary_multiplier: 1.1)
        
        # Seattle phase salary progression (Years 4-10) - with 1.1x multiplier
        salary_array: [110000, 121000, 132000, 165000, 198000, 220000, 220000]
        bonus_array: [0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10]
        rsu_array: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
      
      expense_profile:
        template: "graduate"
        location_overrides:
          rent: { monthly: 2200 }
          healthcare: { monthly: 500 }
          general_expenses: { monthly: 2000 }
          retirement_contribution: { percentage: 0.06 }
      
      life_events:
        - template: "children"
          start_year: 7
          one_off_cost: 8500
          ongoing_annual_cost: 10000
  
  # Housing Strategy - Local Home Purchase in Seattle
  housing:
    strategy: "local_home"           # Buy local home in Seattle
    purchase_year: 3                 # Purchase during Seattle phase (relative to seattle phase start = year 6 overall)
    purchase_price: 750000           # From config.py international_scenarios.seattle.housing_options.local_home.price_usd
    deposit_percentage: 0.25         # From config.py international_scenarios.seattle.housing_options.local_home.deposit_pct
    mortgage_rate: 0.065            # From config.py international_scenarios.seattle.housing_options.local_home.mortgage_rate
    mortgage_term_years: 30         # From config.py international_scenarios.seattle.housing_options.local_home.mortgage_term_years
    price_growth: [0.03, 0.04, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]  # From config.py international_scenarios.seattle.housing_options.local_home.price_growth

# Planning Assumptions - From config.py
assumptions:
  start_year: 2025
  plan_duration_years: 10
  start_age: 24
  student_loan_debt: 57000
  inflation_rate: 0.025
  investment_return_rate: 0.065
  
  # Phase transition details
  relocation:
    year: 4                          # Move to Seattle in year 4
    cost: 11300                      # From config.py international_scenarios.seattle.relocation_cost
    salary_multiplier: 1.1           # From config.py delayed_relocation.seattle_year4_local_home.salary_multiplier
  
  # Currency considerations
  exchange_rate: 1.26               # GBP/USD rate
  
  # Additional expense details from config.py
  personal_expenses:
    year_1: 6000
    year_2: 9000
    default: 12000
  
  parental_support:
    before_house: 12000
    after_house: 12000
    house_purchase_year: 5
  
  travel:
    annual: 3000 