# Seattle Year 5 UK Home - Version 3.0
# Multi-phase scenario: UK for 4 years, then Seattle with UK home purchase

scenario:
  id: "seattle_year5_uk_home"
  name: "Delayed Relocation: Seattle Year 5 - UK Home"
  description: "Work in UK for 4 years, relocate to Seattle in year 5, buy UK home"
  version: "3.0.0"
  tags: ["multi_phase", "delayed_relocation", "seattle", "uk_home"]

composition:
  # Multi-phase career progression
  phases:
    # Phase 1: UK Years (Years 1-4)
    uk_phase:
      duration: 4
      location:
        market: "uk"                 # References config/markets/locations/uk.yaml
      
      salary_progression:
        template: "conservative"     # Use conservative UK progression
        override_type: "complete_array"
        base_salary: 45000
        
        # UK phase salary progression (Years 1-4)
        salary_array: [45000, 52000, 60000, 70000]
        bonus_array: [0.05, 0.08, 0.10, 0.12]
        rsu_array: [0.15, 0.18, 0.20, 0.25]
      
      expense_profile:
        template: "graduate"
        location_overrides:
          rent: { monthly: 2100 }
          healthcare: { monthly: 0 }
          general_expenses: { monthly: 1500 }
          retirement_contribution: { percentage: 0.05 }
      
      life_events:
        - template: "education"
          year: 1
          amount: 16800
          payment_schedule: [5600, 5600, 5600]
        
        - template: "marriage"
          start_year: 3
          end_year: 4
          total_cost: 70000
    
    # Phase 2: Seattle Years (Years 5-10)
    seattle_phase:
      duration: 6
      location:
        market: "us_washington"      # References config/markets/locations/us_washington.yaml
      
      salary_progression:
        template: "tech_worker"      # US tech progression
        override_type: "complete_array"
        base_salary: 120000          # 20% premium for UK experience (salary_multiplier: 1.2)
        
        # Seattle phase salary progression (Years 5-10) - with 1.2x multiplier
        salary_array: [120000, 132000, 144000, 180000, 216000, 240000]
        bonus_array: [0.10, 0.10, 0.10, 0.10, 0.10, 0.10]
        rsu_array: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
      
      expense_profile:
        template: "graduate"
        location_overrides:
          rent: { monthly: 2200 }
          healthcare: { monthly: 500 }
          general_expenses: { monthly: 2000 }
          retirement_contribution: { percentage: 0.06 }
      
      life_events:
        - template: "children"
          start_year: 7
          one_off_cost: 8500
          ongoing_annual_cost: 10000
  
  # Housing Strategy - UK Home Purchase
  housing:
    strategy: "uk_home"              # Buy UK home while living in Seattle
    purchase_year: 5                 # Purchase during Seattle phase (year 5 overall = start of Seattle)
    purchase_price: 575000           # From config.py delayed_relocation scenario
    deposit_percentage: 0.25         # From config.py
    mortgage_rate: 0.0525           # From config.py
    mortgage_term_years: 25         # From config.py
    price_growth: [0.01, 0.04, 0.06, 0.06]
    
    # Rental income while abroad
    rental_income:
      monthly_rent: 2500
      management_fee_percentage: 0.10
      rental_yield: 0.05

# Planning Assumptions - From config.py
assumptions:
  start_year: 2025
  plan_duration_years: 10
  start_age: 24
  student_loan_debt: 57000
  inflation_rate: 0.025
  investment_return_rate: 0.065
  
  # Phase transition details
  relocation:
    year: 5                          # Move to Seattle in year 5
    cost: 11300                      # From config.py international_scenarios.seattle.relocation_cost
    salary_multiplier: 1.2           # From config.py delayed_relocation.seattle_year5_uk_home.salary_multiplier
  
  # Currency considerations
  exchange_rate: 1.26               # GBP/USD rate
  
  # Additional expense details from config.py
  personal_expenses:
    year_1: 6000
    year_2: 9000
    default: 12000
  
  parental_support:
    before_house: 12000
    after_house: 12000
    house_purchase_year: 5
  
  travel:
    annual: 3000 