# Seattle Tech Graduate - Version 3.0
# Seattle tech graduate with aggressive progression using composition-based architecture

scenario:
  id: "seattle_tech_graduate"
  name: "Seattle Tech Graduate - Aggressive Growth"
  description: "Seattle tech graduate with aggressive salary progression and local home focus"
  version: "3.0.0"
  tags: ["international", "seattle", "tech", "aggressive", "local_home"]
  phase: "international_only"
  jurisdiction: "US"

composition:
  # Location Market
  location_market: "us_washington"   # References config/markets/locations/us_washington.yaml
  
  # Tax System
  tax_system: "us_federal"           # References config/tax_systems/us_federal.yaml
  
  # Salary Progression - Aggressive tech progression (different from standard Seattle)
  salary_progression:
    template: "tech_worker"          # Use tech worker template as base
    override_type: "complete_array"  # Override entire progression with exact values
    base_salary: 100000
    
    # Exact salary progression - aggressive tech graduate pattern
    salary_array: [100000, 120000, 144000, 180000, 216000, 240000, 240000, 264000, 264000, 288000]
    
    # Exact bonus progression - aggressive tech graduate pattern
    bonus_array: [0.08, 0.10, 0.12, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
    
    # Exact RSU progression - aggressive tech graduate pattern
    rsu_array: [0.20, 0.22, 0.25, 0.30, 0.30, 0.30, 0.30, 0.30, 0.30, 0.30]
  
  # Expense Profile
  expense_profile: "graduate"        # References config/templates/expense_profiles/graduate.yaml
  
  # Housing Strategy
  housing_strategy: "us_local_home_purchase"  # References config/templates/housing_strategies/us_local_home_purchase.yaml
  
  # Investment Strategy
  investment_strategy: "balanced"    # References config/templates/investment_strategies/balanced.yaml

# Planning Parameters - From config.py
planning:
  start_year: 2025                  # From config.py start_year
  duration_years: 10                # From config.py plan_duration_years  
  start_age: 24                     # From config.py start_age
  currency: "USD"
  inflation_rate: 0.025             # From config.py inflation_rate
  investment_return_rate: 0.065     # From config.py investment_return_rate
  
  # Initial state
  initial_state:
    student_loan_balance: 57000     # From config.py student_loan_debt
    initial_investments: 0
    initial_property_value: 0
    initial_mortgage: 0 