# Seattle Year 5 Local Home - Complete Financial Plan
# Move to Seattle in Year 5, buy local home

scenario:
  id: "seattle_year5_local_home"
  name: "Seattle (Move Year 5) - Buy Local Home"
  description: "Stay in UK for 4 years, then move to Seattle and buy local home"
  version: "2.0.0"
  created: "2025-01-29"

phases:
  uk_phase:
    location:
      name: "United Kingdom"
      currency: "GBP"
      exchange_rate: 1.0
      tax_system: "uk_income_tax_ni"
    duration: 4
    income:
      base_salary: 45000
      progression:
        type: "yearly_overrides"
        rates:
          1: { salary: 45000, bonus: 0.05, rsu: 0.15 }
          2: { salary: 52000, bonus: 0.08, rsu: 0.18 }
          3: { salary: 60000, bonus: 0.10, rsu: 0.20 }
          4: { salary: 70000, bonus: 0.12, rsu: 0.25 }
      rsu_config:
        vesting_schedule: "4_year_cliff"
        ipo_multiplier: 2.0
    expenses:
      location_expenses:
        rent:
          monthly: 2100
          currency: "GBP"
        healthcare:
          monthly: 0
          currency: "GBP"
        general_expenses:
          monthly: 1500
          currency: "GBP"
        retirement_contribution:
          percentage: 0.05
      goals:
        university_fees:
          year: 1
          amount: 16800
          payment_schedule: [5600, 5600, 5600]
          currency: "GBP"
        marriage:
          total_cost: 70000
          start_year: 3
          end_year: 4
          currency: "GBP"
        personal_expenses:
          year_1: 6000
          year_2: 9000
          default: 12000
          currency: "GBP"
        parental_support:
          before_house: 12000
          after_house: 12000
          house_purchase_year: 5
          currency: "GBP"
        travel:
          annual: 3000
          currency: "GBP"
  seattle_phase:
    location:
      name: "Seattle, WA, USA"
      currency: "USD"
      exchange_rate: 1.26
      tax_system: "us_washington"
    duration: 6
    income:
      base_salary: 120000  # 20% premium for experience (salary_multiplier: 1.2)
      progression:
        type: "yearly_overrides"
        rates:
          5: { salary: 120000, bonus: 0.10, rsu: 0.25 }
          6: { salary: 132000, bonus: 0.10, rsu: 0.25 }
          7: { salary: 144000, bonus: 0.10, rsu: 0.25 }
          8: { salary: 180000, bonus: 0.10, rsu: 0.25 }
          9: { salary: 216000, bonus: 0.10, rsu: 0.25 }
          10: { salary: 240000, bonus: 0.10, rsu: 0.25 }
      rsu_config:
        vesting_schedule: "4_year_cliff"
        ipo_multiplier: 3.0
    expenses:
      location_expenses:
        rent:
          monthly: 2200
          currency: "USD"
        healthcare:
          monthly: 500
          currency: "USD"
        general_expenses:
          monthly: 2000
          currency: "USD"
        retirement_contribution:
          percentage: 0.06
      goals:
        marriage:
          total_cost: 70000
          start_year: 3
          end_year: 4
          currency: "GBP"
        child_costs:
          start_year: 7
          one_off_cost: 8500
          ongoing_annual_cost: 10000
          currency: "GBP"
        personal_expenses:
          year_1: 6000
          year_2: 9000
          default: 12000
          currency: "GBP"
        parental_support:
          before_house: 12000
          after_house: 12000
          house_purchase_year: 5
          currency: "GBP"
        travel:
          annual: 3000
          currency: "GBP"
        housing:
          strategy: "local_home"
          purchase_year: 3
          base_price: 750000
          price_growth: [0.03, 0.04, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
          deposit_pct: 0.25
          mortgage_rate: 0.065
          mortgage_term_years: 30
          currency: "USD"
assumptions:
  start_year: 2025
  plan_duration_years: 10
  inflation_rate: 0.025
  investment_return_rate: 0.065
  start_age: 24
  student_loan_debt: 57000
  relocation_cost: 11300 