# UK Aggressive Scenario B - Version 3.0
# Aggressive UK tech graduate path using composition-based architecture

scenario:
  id: "uk_scenario_b"
  name: "UK Aggressive Growth Scenario"
  description: "Aggressive UK career path with higher salary progression and RSU focus"
  version: "3.0.0"
  tags: ["uk", "aggressive", "tech", "homeowner"]
  phase: "uk_only"
  jurisdiction: "UK"

composition:
  # Location Market
  location_market: "uk"              # References config/markets/locations/uk.yaml
  
  # Tax System
  tax_system: "uk_income_tax_ni"     # References config/tax_systems/uk_income_tax_ni.yaml
  
  # Salary Progression - Override with exact values from config.py Scenario B
  salary_progression:
    template: "tech_worker"          # Use tech worker template as base
    override_type: "complete_array"  # Override entire progression with exact values
    base_salary: 50000
    
    # Exact salary progression from config.py UK Scenario B
    salary_array: [50000, 56000, 63000, 70000, 78000, 87000, 98000, 110000, 123000, 138000]
    
    # Exact bonus progression from config.py UK Scenario B
    bonus_array: [0.10, 0.12, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15]
    
    # Exact RSU progression from config.py UK Scenario B
    rsu_array: [0.20, 0.22, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
  
  # Expense Profile
  expense_profile: "graduate"        # References config/templates/expense_profiles/graduate.yaml
  
  # Housing Strategy
  housing_strategy: "uk_home_purchase"  # References config/templates/housing_strategies/uk_home_purchase.yaml
  
  # Investment Strategy
  investment_strategy: "balanced"       # References config/templates/investment_strategies/balanced.yaml

# Planning Parameters - From config.py
planning:
  start_year: 2025                  # From config.py start_year
  duration_years: 10                # From config.py plan_duration_years  
  start_age: 24                     # From config.py start_age
  currency: "GBP"
  inflation_rate: 0.025             # From config.py inflation_rate
  investment_return_rate: 0.065     # From config.py investment_return_rate
  
  # Initial state
  initial_state:
    student_loan_balance: 57000     # From config.py student_loan_debt
    initial_investments: 0
    initial_property_value: 0
    initial_mortgage: 0 