# Scenario Configuration Schema
# JSON Schema for validating scenario configurations with flexible override support

$schema: "http://json-schema.org/draft-07/schema#"
$id: "scenario.schema.yaml"
title: "Financial Planning Scenario"
description: "Schema for validating financial planning scenario configurations"
version: "3.0.0"

type: "object"
required: ["scenario", "composition", "assumptions"]

properties:
  scenario:
    type: "object"
    required: ["id", "name", "version"]
    properties:
      id:
        type: "string"
        pattern: "^[a-z0-9_]+$"
        description: "Unique identifier for the scenario"
      
      name:
        type: "string"
        maxLength: 100
        description: "Human-readable scenario name"
      
      description:
        type: "string"
        maxLength: 500
        description: "Detailed scenario description"
      
      version:
        type: "string"
        pattern: "^\\d+\\.\\d+\\.\\d+$"
        description: "Semantic version number"
      
      tags:
        type: "array"
        items:
          type: "string"
        description: "Tags for categorizing scenarios"

  composition:
    type: "object"
    properties:
      # Single-phase scenarios
      location:
        type: "object"
        properties:
          market:
            type: "string"
            enum: ["uk", "us_washington", "us_new_york", "us_california", "us_texas", "uae_dubai"]
            description: "Reference to location market configuration"
      
      # Multi-phase scenarios
      phases:
        type: "object"
        patternProperties:
          "^[a-z_]+_phase$":
            type: "object"
            required: ["duration", "location", "salary_progression", "expense_profile"]
            properties:
              duration:
                type: "integer"
                minimum: 1
                maximum: 10
                description: "Duration of this phase in years"
              
              location:
                type: "object"
                required: ["market"]
                properties:
                  market:
                    type: "string"
                    enum: ["uk", "us_washington", "us_new_york", "us_california", "us_texas", "uae_dubai"]
              
              salary_progression:
                $ref: "#/definitions/salary_progression"
              
              expense_profile:
                $ref: "#/definitions/expense_profile"
              
              life_events:
                $ref: "#/definitions/life_events"
      
      # Single-phase composition elements
      salary_progression:
        $ref: "#/definitions/salary_progression"
      
      expense_profile:
        $ref: "#/definitions/expense_profile"
      
      life_events:
        $ref: "#/definitions/life_events"
      
      housing:
        $ref: "#/definitions/housing"
    
    # Either single-phase OR multi-phase structure required
    anyOf:
      - required: ["location", "salary_progression", "expense_profile"]
      - required: ["phases", "housing"]

  assumptions:
    type: "object"
    required: ["start_year", "plan_duration_years"]
    properties:
      start_year:
        type: "integer"
        minimum: 2020
        maximum: 2050
        description: "Planning start year"
      
      plan_duration_years:
        type: "integer"
        minimum: 1
        maximum: 50
        description: "Duration of the financial plan"
      
      start_age:
        type: "integer"
        minimum: 18
        maximum: 65
        description: "Starting age"
      
      student_loan_debt:
        type: "number"
        minimum: 0
        description: "Initial student loan debt"
      
      inflation_rate:
        type: "number"
        minimum: -0.1
        maximum: 0.5
        description: "Annual inflation rate"
      
      investment_return_rate:
        type: "number"
        minimum: 0
        maximum: 0.5
        description: "Expected investment return rate"
      
      exchange_rate:
        type: "number"
        minimum: 0.1
        maximum: 10.0
        description: "Currency exchange rate (base to foreign)"
      
      # Multi-phase specific
      relocation:
        type: "object"
        properties:
          year:
            type: "integer"
            minimum: 1
            maximum: 50
          cost:
            type: "number"
            minimum: 0
          salary_multiplier:
            type: "number"
            minimum: 0.5
            maximum: 3.0
      
      # Expense details
      personal_expenses:
        type: "object"
        properties:
          year_1:
            type: "number"
            minimum: 0
          year_2:
            type: "number"
            minimum: 0
          default:
            type: "number"
            minimum: 0
      
      parental_support:
        type: "object"
        properties:
          before_house:
            type: "number"
            minimum: 0
          after_house:
            type: "number"
            minimum: 0
          house_purchase_year:
            type: "integer"
            minimum: 1
            maximum: 50
      
      travel:
        type: "object"
        properties:
          annual:
            type: "number"
            minimum: 0

# Reusable definitions
definitions:
  salary_progression:
    type: "object"
    required: ["template", "base_salary"]
    properties:
      template:
        type: "string"
        enum: ["conservative", "aggressive", "tech_worker"]
        description: "Reference to salary progression template"
      
      base_salary:
        type: "number"
        minimum: 15000
        maximum: 10000000
        description: "Starting base salary"
      
      override_type:
        type: "string"
        enum: ["none", "year_specific", "complete_array", "partial_array", "growth_rates", "external_source"]
        description: "Type of override to apply"
      
      # Array-based overrides
      salary_array:
        type: "array"
        items:
          type: "number"
          minimum: 0
        minItems: 1
        maxItems: 50
        description: "Complete salary array for all years"
      
      bonus_array:
        type: "array"
        items:
          type: "number"
          minimum: 0
          maximum: 2.0
        minItems: 1
        maxItems: 50
        description: "Complete bonus percentage array"
      
      rsu_array:
        type: "array"
        items:
          type: "number"
          minimum: 0
          maximum: 2.0
        minItems: 1
        maxItems: 50
        description: "Complete RSU percentage array"
      
      # Individual year overrides
      overrides:
        type: "object"
        patternProperties:
          "^year_\\d+$":
            type: "object"
            properties:
              salary:
                type: "number"
                minimum: 0
              bonus:
                type: "number"
                minimum: 0
                maximum: 1
              rsu:
                type: "number"
                minimum: 0
                maximum: 1
              reason:
                type: "string"
                description: "Reason for override (promotion, etc.)"

  expense_profile:
    type: "object"
    required: ["template"]
    properties:
      template:
        type: "string"
        enum: ["graduate", "mid_career", "senior"]
        description: "Reference to expense profile template"
      
      location_overrides:
        type: "object"
        properties:
          rent:
            type: "object"
            properties:
              monthly:
                type: "number"
                minimum: 0
          
          healthcare:
            type: "object"
            properties:
              monthly:
                type: "number"
                minimum: 0
          
          general_expenses:
            type: "object"
            properties:
              monthly:
                type: "number"
                minimum: 0
          
          retirement_contribution:
            type: "object"
            properties:
              percentage:
                type: "number"
                minimum: 0
                maximum: 1

  life_events:
    type: "array"
    items:
      type: "object"
      required: ["template"]
      properties:
        template:
          type: "string"
          enum: ["education", "marriage", "children"]
          description: "Reference to life event template"
        
        year:
          type: "integer"
          minimum: 1
          maximum: 50
        
        start_year:
          type: "integer"
          minimum: 1
          maximum: 50
        
        end_year:
          type: "integer"
          minimum: 1
          maximum: 50
        
        amount:
          type: "number"
          minimum: 0
        
        total_cost:
          type: "number"
          minimum: 0
        
        one_off_cost:
          type: "number"
          minimum: 0
        
        ongoing_annual_cost:
          type: "number"
          minimum: 0
        
        payment_schedule:
          type: "array"
          items:
            type: "number"
            minimum: 0

  housing:
    type: "object"
    required: ["strategy", "purchase_year"]
    properties:
      strategy:
        type: "string"
        enum: ["uk_home", "local_home", "rent_only"]
        description: "Housing purchase strategy"
      
      purchase_year:
        type: "integer"
        minimum: 1
        maximum: 50
        description: "Year when property purchase occurs"
      
      purchase_price:
        type: "number"
        minimum: 50000
        maximum: 10000000
        description: "Property purchase price"
      
      deposit_percentage:
        type: "number"
        minimum: 0.05
        maximum: 0.50
        description: "Deposit as percentage of purchase price"
      
      mortgage_rate:
        type: "number"
        minimum: 0.01
        maximum: 0.20
        description: "Annual mortgage interest rate"
      
      mortgage_term_years:
        type: "integer"
        minimum: 5
        maximum: 40
        description: "Mortgage term in years"
      
      price_growth:
        type: "array"
        items:
          type: "number"
          minimum: -0.5
          maximum: 1.0
        description: "Annual property price growth rates"
      
      rental_income:
        type: "object"
        properties:
          monthly_rent:
            type: "number"
            minimum: 0
          management_fee_percentage:
            type: "number"
            minimum: 0
            maximum: 0.30
          rental_yield:
            type: "number"
            minimum: 0
            maximum: 0.20

# Additional validation rules
additionalProperties: false

# Custom validation messages
errorMessage:
  required:
    scenario: "Scenario metadata is required"
    composition: "Composition section is required"
    assumptions: "Assumptions section is required"
  
  properties:
    scenario:
      id: "Scenario ID must be lowercase alphanumeric with underscores"
      version: "Version must follow semantic versioning (x.y.z)"
    
    composition:
      salary_progression:
        base_salary: "Base salary must be between £15,000 and £10,000,000"
        salary_array: "Salary array must contain 1-50 positive values"
        bonus_array: "Bonus array must contain percentages between 0-200%" 