# Texas State Tax Configuration
# Extends US Federal Tax (no state income tax)

tax_system:
  id: "us_texas"
  name: "US Federal + Texas State"
  description: "US federal tax + Texas (no state income tax)"
  version: "2.0.0"
  created: "2025-01-29"
  currency: "USD"
  extends: "us_federal"

state:
  type: "texas"
  income_tax_rate: 0.0  # No state income tax
  description: "Texas has no state income tax" 