# Housing Configuration
# Professional housing market configurations with currency conversion

version: "2.0.0"
metadata:
  created: "2025-01-29"
  author: "Financial Planning System"
  description: "Housing market configurations with rental income modeling"

markets:
  uk:
    name: "United Kingdom"
    currency: "GBP"
    exchange_rate: 1.0
    properties:
      uk_home:
        name: "UK Home"
        description: "UK residential property"
        purchase_year: 5
        base_price: 600000
        price_growth: [0.01, 0.04, 0.06, 0.06]
        deposit_pct: 0.20
        mortgage_rate: 0.0525
        mortgage_term_years: 25
        rental_income:
          when_abroad: true
          monthly_rate: 2500
          management_fee: 0.10
          currency: "GBP"

  seattle:
    name: "Seattle, WA, USA"
    currency: "USD"
    exchange_rate: 1.26
    properties:
      local_home:
        name: "Seattle Home"
        description: "Seattle residential property"
        purchase_year: 3
        base_price: 750000
        price_growth: [0.03, 0.04, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
        deposit_pct: 0.25
        mortgage_rate: 0.065
        mortgage_term_years: 30
        rental_income:
          when_abroad: false
          monthly_rate: 0
          management_fee: 0.0
          currency: "USD"

  new_york:
    name: "New York, NY, USA"
    currency: "USD"
    exchange_rate: 1.26
    properties:
      local_home:
        name: "New York Home"
        description: "New York residential property"
        purchase_year: 4
        base_price: 1200000
        price_growth: [0.04, 0.05, 0.06, 0.06, 0.06, 0.06, 0.06]
        deposit_pct: 0.20
        mortgage_rate: 0.065
        mortgage_term_years: 30
        rental_income:
          when_abroad: false
          monthly_rate: 0
          management_fee: 0.0
          currency: "USD"

  dubai:
    name: "Dubai, UAE"
    currency: "USD"
    exchange_rate: 1.26
    properties:
      local_home:
        name: "Dubai Home"
        description: "Dubai residential property"
        purchase_year: 3
        base_price: 520000
        price_growth: [0.02, 0.03, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04]
        deposit_pct: 0.20
        mortgage_rate: 0.045
        mortgage_term_years: 25
        rental_income:
          when_abroad: false
          monthly_rate: 0
          management_fee: 0.0
          currency: "USD"

strategies:
  uk_home:
    name: "Buy UK Home"
    description: "Buy UK home regardless of current location"
    market: "uk"
    property_type: "uk_home"
    remote_purchase: true
    currency_conversion: true
    rental_income_when_abroad: true

  local_home:
    name: "Buy Local Home"
    description: "Buy home in current location"
    market: "{{current_location}}"
    property_type: "local_home"
    remote_purchase: false
    currency_conversion: false
    rental_income_when_abroad: false

# Housing calculation parameters
calculation:
  inflation_adjustment: true
  currency_conversion_fees: 0.02  # 2% currency conversion fees
  remote_purchase_fees: 0.01      # 1% additional fees for remote purchase
  property_management_fees: 0.10  # 10% property management fees when abroad 