# Salary Templates Configuration
# Professional salary progression templates with year-by-year overrides

version: "2.0.0"
metadata:
  created: "2025-01-29"
  author: "Financial Planning System"
  description: "Salary progression templates with market adjustments"

templates:
  uk_scenario_a:
    name: "UK Scenario A"
    description: "UK tech graduate path A - conservative progression"
    base_salary: 45000
    progression:
      type: "compound_rate"
      rate: 0.15
      max_years: 10
    bonus:
      type: "percentage_of_salary"
      rate: 0.10
      max_percentage: 0.20
    rsu:
      type: "percentage_of_salary"
      rate: 0.20
      vesting_schedule: "4_year_cliff"
      ipo_multiplier: 2.0
    overrides:
      1: { salary: 45000, bonus: 0.05, rsu: 0.15 }
      2: { salary: 52000, bonus: 0.08, rsu: 0.18 }
      3: { salary: 60000, bonus: 0.10, rsu: 0.20 }
      4: { salary: 70000, bonus: 0.12, rsu: 0.25 }
      5: { salary: 80000, bonus: 0.15, rsu: 0.30 }
      6: { salary: 92000, bonus: 0.15, rsu: 0.30 }
      7: { salary: 106000, bonus: 0.15, rsu: 0.30 }
      8: { salary: 122000, bonus: 0.15, rsu: 0.30 }
      9: { salary: 140000, bonus: 0.15, rsu: 0.30 }
      10: { salary: 161000, bonus: 0.15, rsu: 0.30 }

  uk_scenario_b:
    name: "UK Scenario B"
    description: "UK tech graduate path B - aggressive progression"
    base_salary: 50000
    progression:
      type: "compound_rate"
      rate: 0.12
      max_years: 10
    bonus:
      type: "percentage_of_salary"
      rate: 0.15
      max_percentage: 0.25
    rsu:
      type: "percentage_of_salary"
      rate: 0.25
      vesting_schedule: "4_year_cliff"
      ipo_multiplier: 2.0
    overrides:
      1: { salary: 50000, bonus: 0.10, rsu: 0.20 }
      2: { salary: 56000, bonus: 0.12, rsu: 0.22 }
      3: { salary: 63000, bonus: 0.15, rsu: 0.25 }
      4: { salary: 70000, bonus: 0.15, rsu: 0.25 }
      5: { salary: 78000, bonus: 0.15, rsu: 0.25 }
      6: { salary: 87000, bonus: 0.15, rsu: 0.25 }
      7: { salary: 98000, bonus: 0.15, rsu: 0.25 }
      8: { salary: 110000, bonus: 0.15, rsu: 0.25 }
      9: { salary: 123000, bonus: 0.15, rsu: 0.25 }
      10: { salary: 138000, bonus: 0.15, rsu: 0.25 }

  seattle_tech_graduate:
    name: "Seattle Tech Graduate"
    description: "Standard Seattle tech graduate progression"
    base_salary: 100000
    progression:
      type: "compound_rate"
      rate: 0.20
      max_years: 10
    bonus:
      type: "percentage_of_salary"
      rate: 0.10
      max_percentage: 0.30
    rsu:
      type: "percentage_of_salary"
      rate: 0.25
      vesting_schedule: "4_year_cliff"
      ipo_multiplier: 3.0
    overrides:
      1: { salary: 100000, bonus: 0.08, rsu: 0.20 }
      2: { salary: 120000, bonus: 0.10, rsu: 0.22 }
      3: { salary: 144000, bonus: 0.12, rsu: 0.25 }
      4: { salary: 180000, bonus: 0.15, rsu: 0.30 }
      5: { salary: 216000, bonus: 0.15, rsu: 0.30 }
      6: { salary: 240000, bonus: 0.15, rsu: 0.30 }
      7: { salary: 240000, bonus: 0.15, rsu: 0.30 }
      8: { salary: 264000, bonus: 0.15, rsu: 0.30 }
      9: { salary: 264000, bonus: 0.15, rsu: 0.30 }
      10: { salary: 288000, bonus: 0.15, rsu: 0.30 }

  new_york_tech_graduate:
    name: "New York Tech Graduate"
    description: "Standard New York tech graduate progression"
    base_salary: 100000
    progression:
      type: "compound_rate"
      rate: 0.25
      max_years: 10
    bonus:
      type: "percentage_of_salary"
      rate: 0.15
      max_percentage: 0.35
    rsu:
      type: "percentage_of_salary"
      rate: 0.25
      vesting_schedule: "4_year_cliff"
      ipo_multiplier: 3.0
    overrides:
      1: { salary: 100000, bonus: 0.12, rsu: 0.20 }
      2: { salary: 125000, bonus: 0.15, rsu: 0.22 }
      3: { salary: 156000, bonus: 0.15, rsu: 0.25 }
      4: { salary: 195000, bonus: 0.15, rsu: 0.30 }
      5: { salary: 244000, bonus: 0.15, rsu: 0.30 }
      6: { salary: 300000, bonus: 0.15, rsu: 0.30 }
      7: { salary: 300000, bonus: 0.15, rsu: 0.30 }
      8: { salary: 300000, bonus: 0.15, rsu: 0.30 }
      9: { salary: 345000, bonus: 0.15, rsu: 0.30 }
      10: { salary: 375000, bonus: 0.15, rsu: 0.30 }

  dubai_tech_graduate:
    name: "Dubai Tech Graduate"
    description: "Standard Dubai tech graduate progression"
    base_salary: 90000
    progression:
      type: "compound_rate"
      rate: 0.15
      max_years: 10
    bonus:
      type: "percentage_of_salary"
      rate: 0.10
      max_percentage: 0.20
    rsu:
      type: "percentage_of_salary"
      rate: 0.10
      vesting_schedule: "4_year_cliff"
      ipo_multiplier: 2.0
    overrides:
      1: { salary: 90000, bonus: 0.08, rsu: 0.08 }
      2: { salary: 103500, bonus: 0.10, rsu: 0.10 }
      3: { salary: 119000, bonus: 0.10, rsu: 0.10 }
      4: { salary: 137000, bonus: 0.10, rsu: 0.10 }
      5: { salary: 157000, bonus: 0.10, rsu: 0.10 }
      6: { salary: 181000, bonus: 0.10, rsu: 0.10 }
      7: { salary: 208000, bonus: 0.10, rsu: 0.10 }
      8: { salary: 239000, bonus: 0.10, rsu: 0.10 }
      9: { salary: 275000, bonus: 0.10, rsu: 0.10 }
      10: { salary: 316000, bonus: 0.10, rsu: 0.10 }

market_adjustments:
  seattle:
    salary_multiplier: 1.0
    bonus_multiplier: 1.0
    rsu_multiplier: 1.0
  new_york:
    salary_multiplier: 1.2
    bonus_multiplier: 1.3
    rsu_multiplier: 1.1
  dubai:
    salary_multiplier: 0.8
    bonus_multiplier: 0.7
    rsu_multiplier: 0.5 